"""add likes to posts

Revision ID: 28ee848aa5c3
Revises: 74f71067bbbc
Create Date: 2026-07-05 11:09:58.146636

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28ee848aa5c3"
down_revision: Union[str, Sequence[str], None] = "74f71067bbbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("likes", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "likes")
    # ### end Alembic commands ###
