"""add cascade delete to post_tag foreign keys

Revision ID: 79995042a932
Revises: a2918d6dc997
Create Date: 2026-07-12 19:46:47.348438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79995042a932'
down_revision: Union[str, Sequence[str], None] = 'a2918d6dc997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('post_tag_tag_id_fkey'), 'post_tag', type_='foreignkey')
    op.drop_constraint(op.f('post_tag_post_id_fkey'), 'post_tag', type_='foreignkey')
    op.create_foreign_key(None, 'post_tag', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_tag', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tag', type_='foreignkey')
    op.drop_constraint(None, 'post_tag', type_='foreignkey')
    op.create_foreign_key(op.f('post_tag_post_id_fkey'), 'post_tag', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(op.f('post_tag_tag_id_fkey'), 'post_tag', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
